# Generated by Django 3.1.7 on 2021-03-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventplannerapi', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
