# Generated by Django 3.1.7 on 2021-03-06 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventplannerapi', '0003_foodtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50)),
                ('eventdate', models.DateField()),
                ('venue', models.CharField(max_length=70)),
                ('content', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=None)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventplannerapi.category')),
                ('eventUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventplannerapi.eventuser')),
            ],
        ),
    ]
