# Generated by Django 3.1.7 on 2021-03-06 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventplannerapi', '0004_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPlanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_label', models.CharField(max_length=100)),
                ('eventsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Eventplannerapi.events')),
                ('food_TableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodtable', to='Eventplannerapi.foodtable')),
            ],
        ),
    ]
