# Generated by Django 3.1.7 on 2021-03-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventplannerapi', '0005_foodplanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventuser',
            old_name='created_on',
            new_name='createdOn',
        ),
        migrations.RenameField(
            model_name='eventuser',
            old_name='user',
            new_name='userId',
        ),
    ]
