# Generated by Django 3.1.7 on 2021-03-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventplannerapi', '0006_auto_20210307_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodplanner',
            old_name='food_label',
            new_name='foodLabel',
        ),
        migrations.RenameField(
            model_name='foodplanner',
            old_name='food_TableId',
            new_name='foodTableId',
        ),
    ]
